esphome:
  name: ${node_name}
  friendly_name: ${node_name_friendly}
  project:
    name: ${node_project_name}
    version: ${node_project_version}
  name_add_mac_suffix: ${node_name_add_mac_suffix}
  min_version: ${node_build_min_version}

esp8266:
  board: esp12e
  restore_from_flash: false  

wifi:
  id: id_wifi
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  reboot_timeout: 0s
  ap:
    ssid: "${node_name} hotspot"
    password: !secret ap_password
    ap_timeout: 60s

logger:
    level: INFO
api:
  reboot_timeout: 0s
ota:
  password: !secret ota_password

#web_server:
#  port: 80
#  include_internal: true
#  version: 2

switch:
  - platform: restart
    name: "system-Restart"
    id: id_restart

  - platform: factory_reset
    name: "system-FactoryReset"
    id: id_factoryreset

  - platform: safe_mode
    name: "system-OTA-SafeMode"
    id: id_ota_save_mode
