#------- User configure START -------
substitutions:
  config_version: 'v2025.10.24'
  #设备名称（多个dc1改成不一样的，API接入和ESPHOME容器会识别这个作为名称显示）
  device_name: bookshelf_dc1
  #限制异常电流/功率值
  cse7766_max_current: '3'
  cse7766_max_power: '660'
  #开关名称
  output0_name: "USB"
  output1_name: "router"
  output2_name: "soundbox"
  output3_name: "monitor"
  output0_restore_mode: "ALWAYS_ON"
  output1_restore_mode: "ALWAYS_OFF"
  output2_restore_mode: "ALWAYS_OFF"
  output3_restore_mode: "ALWAYS_ON"
  # turn off USB if all other switchs off
  usb_auto_off: '1'
  #不同的log等级看到的信息详细程度不一样，信息量从少到多依次为
  # NONE、ERROR、WARN、INFO、DEBUG、VERBOSE、VERY_VERBOSE
  #LOG_LEVEL: "VERBOSE"
  #LOG_LEVEL: "DEBUG"
  #LOG_LEVEL: "INFO"

packages:
  foo: !include phicomm_dc1_api.yaml
