#------- User configure START -------
substitutions:
  config_version: 'v2025.10.20'
  #设备名称（多个dc1改成不一样的，API接入和ESPHOME容器会识别这个作为名称显示）
  device_name: livingroom
  #限制异常电流/功率值
  cse7766_max_current: '3'
  cse7766_max_power: '660'
  #开关名称
  output0_name: "USB"
  output1_name: "LeChengTP1"
  output2_name: "TmallGenie"
  output3_name: "XiaomiSpeaker"
  output0_restore_mode: "ALWAYS_ON"
  output1_restore_mode: "ALWAYS_ON"
  output2_restore_mode: "ALWAYS_OFF"
  output3_restore_mode: "ALWAYS_OFF"

packages:
  foo: !include phicomm_dc1_api.yaml
