substitutions:
  node_name: "livingroom"
  node_name_friendly: ${node_name}
  node_name_add_mac_suffix: "false"

  # 主从继电器
  master_relay_name: "UNUSED"
  slave_relay_name: "speaaker"
  master_relay_restore_mode: "ALWAYS_OFF"
  slave_relay_restore_mode: "ALWAYS_OFF"

  #不同的log等级看到的信息详细程度不一样，信息量从少到多依次为
  # NONE、ERROR、WARN、INFO、DEBUG、VERBOSE、VERY_VERBOSE
  #LOG_LEVEL: "VERBOSE"
  #LOG_LEVEL: "DEBUG"
  #LOG_LEVEL: "INFO"


packages:
  foo: !include cmpower_w1_1relay.yaml

